"""Исходы хоста для Envelope: перечисление имён и множество ступени метрики. Лист: ни Blender, ни остального хоста.

Вынесено из `envelope_request_export.py` (потолок размера модуля), который переэкспортирует оба имени: всё, что импортировало их
оттуда, работает как прежде.

ИМЯ ИСХОДА ЯДРА И ИМЯ ХОСТА СОВПАДАЮТ БУКВА В БУКВУ (`host_outcome_for`). Прежде хост зеркалил не все отказы ступени метрики:
восемнадцать имён (`SOURCE_SNAP_*`, `NEAR_PLANAR_PROJECTION_*`, `NEAR_PLANAR_REDUCED_FRAME_REQUIRES_SOURCE_SNAP`) сводились к
`ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED`, и поле читало «этап конвейера упал» там, где ядро точно назвало причину (полевой случай
`cover.008`, патчи 18 и 285). Сведения больше нет: исход ядра, которому нет имени здесь, не молчит, а сохраняет своё имя в начале
текста отказа (`refusal_text`), и тест полноты (`tests/test_envelope_host_outcome_mirror.py`) делает такой пропуск красным.
"""

from __future__ import annotations

from enum import Enum


class EnvelopeDebugHostOutcome(str, Enum):
    EXACT = "EXACT"
    ENVELOPE_DEBUG_KERNEL_UNAVAILABLE = "ENVELOPE_DEBUG_KERNEL_UNAVAILABLE"
    ENVELOPE_DEBUG_SYMPY_VERSION_UNSUPPORTED = "ENVELOPE_DEBUG_SYMPY_VERSION_UNSUPPORTED"
    ENVELOPE_DEBUG_ANALYSIS_SNAPSHOT_INVALID = "ENVELOPE_DEBUG_ANALYSIS_SNAPSHOT_INVALID"
    ENVELOPE_DEBUG_EXACT_PLANAR_FRAME_UNAVAILABLE = "ENVELOPE_DEBUG_EXACT_PLANAR_FRAME_UNAVAILABLE"
    RUNTIME_NEAR_PLANAR_PROJECTION_POLICY_REQUIRED = "RUNTIME_NEAR_PLANAR_PROJECTION_POLICY_REQUIRED"
    # Отказы метрики выходят каждый под СВОИМ именем. Прежде хост сводил их все
    # к `RUNTIME_NEAR_PLANAR_PROJECTION_POLICY_REQUIRED`, и поле читало «нужна
    # near-planar политика» ровно тогда, когда она уже была включена, а отказал
    # бюджет. Имя не на ту причину дороже отсутствующего.
    NEAR_PLANAR_RESIDUAL_BUDGET_EXCEEDED = "NEAR_PLANAR_RESIDUAL_BUDGET_EXCEEDED"
    NEAR_PLANAR_WIDTH_DISTORTION_BUDGET_EXCEEDED = "NEAR_PLANAR_WIDTH_DISTORTION_BUDGET_EXCEEDED"
    NEAR_PLANAR_OWNER_TRIANGLE_DEGENERATE = "NEAR_PLANAR_OWNER_TRIANGLE_DEGENERATE"
    NEAR_PLANAR_SOURCE_TRIANGLE_FOLDED = "NEAR_PLANAR_SOURCE_TRIANGLE_FOLDED"
    NEAR_PLANAR_OWNER_SURFACE_TRIANGLES_UNAVAILABLE = "NEAR_PLANAR_OWNER_SURFACE_TRIANGLES_UNAVAILABLE"
    # Остальные отказы ступени метрики ядра (привязка источника к решётке и проекция на плоскость патча) выходят ТЕМ ЖЕ именем,
    # что у ядра: до этого среза хост сводил их все к `ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED`, и имя причины пропадало.
    # Полноту держит `tests/test_envelope_host_outcome_mirror.py`: новый исход ядра без хост-имени там красный.
    NEAR_PLANAR_REDUCED_FRAME_REQUIRES_SOURCE_SNAP = "NEAR_PLANAR_REDUCED_FRAME_REQUIRES_SOURCE_SNAP"
    SOURCE_SNAP_VERTEX_INJECTIVITY_VIOLATED = "SOURCE_SNAP_VERTEX_INJECTIVITY_VIOLATED"
    SOURCE_SNAP_NONZERO_EDGE_COLLAPSED = "SOURCE_SNAP_NONZERO_EDGE_COLLAPSED"
    SOURCE_SNAP_NEW_NONADJACENT_EDGE_INTERSECTION = "SOURCE_SNAP_NEW_NONADJACENT_EDGE_INTERSECTION"
    SOURCE_SNAP_INTENDED_RIGHT_CORNER_DEGENERATED = "SOURCE_SNAP_INTENDED_RIGHT_CORNER_DEGENERATED"
    NEAR_PLANAR_PROJECTION_BOUNDARY_INJECTIVITY_VIOLATED = "NEAR_PLANAR_PROJECTION_BOUNDARY_INJECTIVITY_VIOLATED"
    NEAR_PLANAR_PROJECTION_NONZERO_BOUNDARY_EDGE_COLLAPSED = "NEAR_PLANAR_PROJECTION_NONZERO_BOUNDARY_EDGE_COLLAPSED"
    NEAR_PLANAR_PROJECTION_NEW_NONADJACENT_EDGE_INTERSECTION = "NEAR_PLANAR_PROJECTION_NEW_NONADJACENT_EDGE_INTERSECTION"
    NEAR_PLANAR_PROJECTION_NEW_COLLINEAR_EDGE_OVERLAP = "NEAR_PLANAR_PROJECTION_NEW_COLLINEAR_EDGE_OVERLAP"
    NEAR_PLANAR_PROJECTION_LOOP_ORIENTATION_CHANGED = "NEAR_PLANAR_PROJECTION_LOOP_ORIENTATION_CHANGED"
    NEAR_PLANAR_PROJECTION_BOUNDARY_COMPONENT_COUNT_CHANGED = "NEAR_PLANAR_PROJECTION_BOUNDARY_COMPONENT_COUNT_CHANGED"
    NEAR_PLANAR_PROJECTION_OUTER_HOLE_NESTING_CHANGED = "NEAR_PLANAR_PROJECTION_OUTER_HOLE_NESTING_CHANGED"
    NEAR_PLANAR_PROJECTION_SOURCE_ANCHOR_IDENTITY_CHANGED = "NEAR_PLANAR_PROJECTION_SOURCE_ANCHOR_IDENTITY_CHANGED"
    NEAR_PLANAR_PROJECTION_RESOLVED_PLANE_BASIS_UNAVAILABLE = "NEAR_PLANAR_PROJECTION_RESOLVED_PLANE_BASIS_UNAVAILABLE"
    NEAR_PLANAR_PROJECTION_FAN_IDENTITY_CHANGED = "NEAR_PLANAR_PROJECTION_FAN_IDENTITY_CHANGED"
    NEAR_PLANAR_PROJECTION_VERTEX_INJECTIVITY_VIOLATED = "NEAR_PLANAR_PROJECTION_VERTEX_INJECTIVITY_VIOLATED"
    NEAR_PLANAR_PROJECTION_FACE_POLYGON_NOT_SIMPLE = "NEAR_PLANAR_PROJECTION_FACE_POLYGON_NOT_SIMPLE"
    NEAR_PLANAR_PROJECTION_INTERIOR_OVERLAP = "NEAR_PLANAR_PROJECTION_INTERIOR_OVERLAP"
    GRID_WINDOW_CLOSED = "GRID_WINDOW_CLOSED"
    NO_POWER_OF_TWO_STEP_IN_WINDOW = "NO_POWER_OF_TWO_STEP_IN_WINDOW"
    NO_GRID_SCALE_RESTORES_RELATIONS = "NO_GRID_SCALE_RESTORES_RELATIONS"
    DEVELOPABLE_ADJACENCY_UNAVAILABLE = "DEVELOPABLE_ADJACENCY_UNAVAILABLE"
    DEVELOPABLE_SUPPORT_NOT_A_DISK = "DEVELOPABLE_SUPPORT_NOT_A_DISK"
    PERIODIC_CUT_REQUIRED = "PERIODIC_CUT_REQUIRED"
    DEVELOPABLE_SOURCE_TRIANGLE_DEGENERATE = "DEVELOPABLE_SOURCE_TRIANGLE_DEGENERATE"
    DEVELOPABLE_REQUIRES_SOURCE_SNAP = "DEVELOPABLE_REQUIRES_SOURCE_SNAP"
    DEVELOPABLE_STRETCH_BUDGET_EXCEEDED = "DEVELOPABLE_STRETCH_BUDGET_EXCEEDED"
    DEVELOPABLE_CHART_TRIANGLE_FLIPPED = "DEVELOPABLE_CHART_TRIANGLE_FLIPPED"
    DEVELOPABLE_CHART_SELF_OVERLAP = "DEVELOPABLE_CHART_SELF_OVERLAP"
    DEVELOPABLE_CHART_LATTICE_TOO_COARSE = "DEVELOPABLE_CHART_LATTICE_TOO_COARSE"
    DEVELOPABLE_DECLARED_STRAIGHT_CHAIN_BENT = "DEVELOPABLE_DECLARED_STRAIGHT_CHAIN_BENT"
    DEVELOPABLE_BAND_SUPPORT_DISCONNECTED = "DEVELOPABLE_BAND_SUPPORT_DISCONNECTED"
    CHART_REACH_SHORT_OF_CAP = "CHART_REACH_SHORT_OF_CAP"
    DEVELOPABLE_BAND_BOUNDARY_UNRESOLVED = "DEVELOPABLE_BAND_BOUNDARY_UNRESOLVED"
    REQUEST_ALPHA_EXCEEDS_CHART_REACH = "REQUEST_ALPHA_EXCEEDS_CHART_REACH"
    PERIODIC_CUT_PATH_UNAVAILABLE = "PERIODIC_CUT_PATH_UNAVAILABLE"
    PERIODIC_CUT_SEAM_RESIDUAL_EXCEEDED = "PERIODIC_CUT_SEAM_RESIDUAL_EXCEEDED"
    PERIODIC_CUT_BISECTOR_DEVIATION_EXCEEDED = "PERIODIC_CUT_BISECTOR_DEVIATION_EXCEEDED"
    ENVELOPE_DEBUG_EXACT_ANGULAR_CERTIFICATE_UNAVAILABLE = "ENVELOPE_DEBUG_EXACT_ANGULAR_CERTIFICATE_UNAVAILABLE"
    ENVELOPE_DEBUG_MULTIPLE_ANGULAR_RELATIONS_PER_CHAIN_UNSUPPORTED = "ENVELOPE_DEBUG_MULTIPLE_ANGULAR_RELATIONS_PER_CHAIN_UNSUPPORTED"
    ENVELOPE_DEBUG_PHYSICAL_CHAIN_INVALID = "ENVELOPE_DEBUG_PHYSICAL_CHAIN_INVALID"
    ENVELOPE_DEBUG_CHAIN_USE_PAIR_UNAVAILABLE = "ENVELOPE_DEBUG_CHAIN_USE_PAIR_UNAVAILABLE"
    ENVELOPE_DEBUG_SELF_SEAM_USE_PAIR_UNAVAILABLE = "ENVELOPE_DEBUG_SELF_SEAM_USE_PAIR_UNAVAILABLE"
    ENVELOPE_DEBUG_EMPTY_SELECTION = "ENVELOPE_DEBUG_EMPTY_SELECTION"
    ENVELOPE_DEBUG_SELECTED_EDGE_UNKNOWN = "ENVELOPE_DEBUG_SELECTED_EDGE_UNKNOWN"
    ENVELOPE_DEBUG_PARTIAL_CHAIN_SELECTION_UNSUPPORTED = "ENVELOPE_DEBUG_PARTIAL_CHAIN_SELECTION_UNSUPPORTED"
    ENVELOPE_DEBUG_SELECTED_EDGE_OFF_PHYSICAL_CHAIN = "ENVELOPE_DEBUG_SELECTED_EDGE_OFF_PHYSICAL_CHAIN"
    # Предполёт ИСТОЧНИКА (`envelope_source_contacts`): имена хоста, ядро их не бросает. Зазор — `SOURCE_CONTACT_GAP_V1` реестра допусков.
    SOURCE_T_VERTEX = "SOURCE_T_VERTEX"
    SOURCE_FACE_SELF_INTERSECTION = "SOURCE_FACE_SELF_INTERSECTION"
    ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED = "ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED"


# Отказы, случившиеся НА СТУПЕНИ МЕТРИКИ (все — из
# `PlanarMetricAdmissionError`). Ступень домена определяется тем, ГДЕ отказ
# произошёл, а не тем, как он назван, поэтому разведение схлопнутого имени не
# должно молча переносить домен на другую ступень. Исходы развёртки (S1) — тоже ступень
# метрики: лестница кривизны живёт внутри построителя метрики.
METRIC_STAGE_OUTCOMES = frozenset(
    {
        EnvelopeDebugHostOutcome.ENVELOPE_DEBUG_EXACT_PLANAR_FRAME_UNAVAILABLE, EnvelopeDebugHostOutcome.RUNTIME_NEAR_PLANAR_PROJECTION_POLICY_REQUIRED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_RESIDUAL_BUDGET_EXCEEDED, EnvelopeDebugHostOutcome.NEAR_PLANAR_WIDTH_DISTORTION_BUDGET_EXCEEDED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_OWNER_TRIANGLE_DEGENERATE, EnvelopeDebugHostOutcome.NEAR_PLANAR_SOURCE_TRIANGLE_FOLDED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_OWNER_SURFACE_TRIANGLES_UNAVAILABLE, EnvelopeDebugHostOutcome.GRID_WINDOW_CLOSED,
        EnvelopeDebugHostOutcome.NO_POWER_OF_TWO_STEP_IN_WINDOW, EnvelopeDebugHostOutcome.NO_GRID_SCALE_RESTORES_RELATIONS,
        EnvelopeDebugHostOutcome.DEVELOPABLE_ADJACENCY_UNAVAILABLE, EnvelopeDebugHostOutcome.DEVELOPABLE_SUPPORT_NOT_A_DISK,
        EnvelopeDebugHostOutcome.PERIODIC_CUT_REQUIRED, EnvelopeDebugHostOutcome.DEVELOPABLE_SOURCE_TRIANGLE_DEGENERATE,
        EnvelopeDebugHostOutcome.DEVELOPABLE_REQUIRES_SOURCE_SNAP, EnvelopeDebugHostOutcome.DEVELOPABLE_STRETCH_BUDGET_EXCEEDED,
        EnvelopeDebugHostOutcome.DEVELOPABLE_CHART_TRIANGLE_FLIPPED, EnvelopeDebugHostOutcome.DEVELOPABLE_CHART_SELF_OVERLAP,
        EnvelopeDebugHostOutcome.DEVELOPABLE_CHART_LATTICE_TOO_COARSE, EnvelopeDebugHostOutcome.DEVELOPABLE_DECLARED_STRAIGHT_CHAIN_BENT,
        EnvelopeDebugHostOutcome.DEVELOPABLE_BAND_SUPPORT_DISCONNECTED, EnvelopeDebugHostOutcome.CHART_REACH_SHORT_OF_CAP,
        EnvelopeDebugHostOutcome.DEVELOPABLE_BAND_BOUNDARY_UNRESOLVED, EnvelopeDebugHostOutcome.PERIODIC_CUT_PATH_UNAVAILABLE,
        EnvelopeDebugHostOutcome.PERIODIC_CUT_SEAM_RESIDUAL_EXCEEDED, EnvelopeDebugHostOutcome.PERIODIC_CUT_BISECTOR_DEVIATION_EXCEEDED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_REDUCED_FRAME_REQUIRES_SOURCE_SNAP, EnvelopeDebugHostOutcome.SOURCE_SNAP_VERTEX_INJECTIVITY_VIOLATED,
        EnvelopeDebugHostOutcome.SOURCE_SNAP_NONZERO_EDGE_COLLAPSED, EnvelopeDebugHostOutcome.SOURCE_SNAP_NEW_NONADJACENT_EDGE_INTERSECTION,
        EnvelopeDebugHostOutcome.SOURCE_SNAP_INTENDED_RIGHT_CORNER_DEGENERATED, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_BOUNDARY_INJECTIVITY_VIOLATED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_NONZERO_BOUNDARY_EDGE_COLLAPSED, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_NEW_NONADJACENT_EDGE_INTERSECTION,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_NEW_COLLINEAR_EDGE_OVERLAP, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_LOOP_ORIENTATION_CHANGED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_BOUNDARY_COMPONENT_COUNT_CHANGED, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_OUTER_HOLE_NESTING_CHANGED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_SOURCE_ANCHOR_IDENTITY_CHANGED, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_RESOLVED_PLANE_BASIS_UNAVAILABLE,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_FAN_IDENTITY_CHANGED, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_VERTEX_INJECTIVITY_VIOLATED,
        EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_FACE_POLYGON_NOT_SIMPLE, EnvelopeDebugHostOutcome.NEAR_PLANAR_PROJECTION_INTERIOR_OVERLAP,
        EnvelopeDebugHostOutcome.SOURCE_T_VERTEX, EnvelopeDebugHostOutcome.SOURCE_FACE_SELF_INTERSECTION,
    }
)


def host_outcome_for(outcome):
    """Исход ядра - в исход хоста, ПО ИМЕНИ, а не таблицей соответствий.

    Имя ядра и имя хоста обязаны совпадать: расхождение означало бы, что поле
    читает одно, а лог ядра говорит другое. Неизвестное имя не подменяется
    ближайшим - иначе новый исход ядра молча выходил бы под чужим; общий
    `ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED` остаётся запасным именем, но
    `refusal_text` ставит имя ядра в начало текста, а тест полноты не пускает
    в запас ни одного отказа ступени метрики.
    """

    try:
        return EnvelopeDebugHostOutcome(outcome.value)
    except ValueError:
        return EnvelopeDebugHostOutcome.ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED


def refusal_text(host_outcome, kernel_outcome, text: str) -> str:
    """Текст отказа хоста: имя ядра не теряется, даже если для него нет имени хоста (тогда оно стоит в начале)."""

    if host_outcome is EnvelopeDebugHostOutcome.ENVELOPE_DEBUG_PIPELINE_STAGE_FAILED:
        return f"{kernel_outcome.value}: {text}"
    return text


__all__ = (
    "METRIC_STAGE_OUTCOMES",
    "EnvelopeDebugHostOutcome",
    "host_outcome_for",
    "refusal_text",
)
