"""Explicit public API for the Blender-free Envelope contract package."""

from importlib import import_module as _import_module
from sys import modules as _modules
from types import ModuleType as _ModuleType


# Имена модулей сохранены как данные: фасад не импортирует их до обращения к
# конкретному публичному имени.
_PUBLIC_VALUE_MODULES = (
    "cftuv_envelope.ids",
    "cftuv_envelope.numeric",
    "cftuv_envelope.outcomes",
    "cftuv_envelope.contracts.analysis",
    "cftuv_envelope.contracts.coverage",
    "cftuv_envelope.contracts.envelopes",
    "cftuv_envelope.contracts.events",
    "cftuv_envelope.contracts.geometry_batch",
    "cftuv_envelope.contracts.metric",
    "cftuv_envelope.contracts.ownership",
    "cftuv_envelope.contracts.plan",
    "cftuv_envelope.contracts.request",
    "cftuv_envelope.contracts.seeds",
    "cftuv_envelope.contracts.surface",
    "cftuv_envelope.contracts.tessellation",
    "cftuv_envelope.contracts.debug",
)

__all__ = (
    "__version__",
    "AnalysisSnapshotCodecV1",
    "CompiledPlanCodecV1",
    "ChainStraightEvaluationGeometryBindingCodecV2",
    "ContractCodecError",
    "DecalRequestCodecV1",
    "EvaluationGeometryBindingCodecV1",
    "GeometryBatchCodecV1",
    "RationalAffinePlanarMetricCodecV2",
    "RuntimePlanarMetricCodecV1",
    "EnvelopeDebugSceneCodecV1",
    "canonical_json_bytes",
    "SnapshotDigest",
    "SemanticPlanDigest",
    "GeometryBatchSemanticDigest",
    "snapshot_digest",
    "semantic_plan_digest",
    "geometry_batch_semantic_digest",
    "compile_reference_envelopes",
    "declare_reference_self_contacts",
    "evaluate_reference_raw_coverage",
    "REFERENCE_BOUNDARY_CAPABILITIES_V1",
    "BoundaryRole",
    "BlockingBoundarySegment",
    "SparsePatchDomainGeometryV1",
    "build_sparse_patch_domain_geometry",
    "RawCoverageSemanticDigest",
    "raw_coverage_semantic_projection",
    "raw_coverage_semantic_digest",
    "validate_raw_coverage_digest",
    "validate_raw_coverage_semantic_digest",
    "resolve_coverage_interactions",
    "compile_interaction_components",
    "compile_arrival_models",
    "generate_interaction_candidates",
    "prove_mutual_arrivals",
    "validate_interaction_inputs",
    "ResolvedCoverageSemanticDigest",
    "resolved_coverage_semantic_projection",
    "resolved_coverage_semantic_digest",
    "validate_resolved_coverage_digest",
    "RESOLVED_COVERAGE_RESULT_SCHEMA_V1",
    "INTRAPATCH_POLICY_B_V1",
    "SELF_CONTACT_POLICY_B_V1",
    "InteractionOutcome",
    "InteractionProvenanceV1",
    "InteractionDiagnosticSeverity",
    "ArrivalModelKind",
    "InteractionCandidateKind",
    "EqualityLocusOwner",
    "InteractionCoverageEffect",
    "FreezeState",
    "InteractionDiagnosticV1",
    "InteractionComponentV1",
    "ExactFrontArrivalLawV1",
    "StripArrivalModelV1",
    "AngularProfileArrivalModelV1",
    "CapArrivalModelV1",
    "UnsupportedJunctionArrivalModelV1",
    "ArrivalModelV1",
    "InteractionCandidateV1",
    "FrontArrivalReadingV1",
    "ActiveDomainCertificateV1",
    "MutualArrivalCertificateV1",
    "EqualityLocusSegmentV1",
    "EqualityLocusV1",
    "ResolvedContributionV1",
    "InteractionApplicationV1",
    "ResolvedCoverageResultV1",
    "InteractionResolutionResultV1",
    "REFERENCE_COMPILATION_SCHEMA_V1",
    "RAW_COVERAGE_RESULT_SCHEMA_V1",
    "RAW_COVERAGE_RESULT_SCHEMA_V2",
    "ReferenceOutcome",
    "ReferenceDiagnosticSeverity",
    "BoundaryContactKind",
    "RawCoverageLoopKind",
    "ReferenceProvenanceV1",
    "BoundaryGeneratorProvenanceV1",
    "CoverageContributorProvenanceV1",
    "ExactPlanarMetric",
    "dot_G",
    "length_G",
    "unit_G",
    "owner_normal_G",
    "distance_to_support_G",
    "offset_support_G",
    "angle_G",
    "ReferenceEvaluationDiagnosticV1",
    "EnvelopeSourceProvenanceV1",
    "ReferenceEnvelopeCompilationV1",
    "ReferenceCompileResultV1",
    "ReferenceEnvelopeInstanceV1",
    "ReachabilityCertificateV1",
    "BoundaryResolvedEnvelopeV1",
    "RawCoverageVertexV1",
    "BoundaryVertexOccurrenceV1",
    "PointContactRecordV1",
    "RawCoverageEdgeV1",
    "RawCoverageLoopV1",
    "RawCoverageRegionV1",
    "ComponentEffectiveAlphaV1",
    "RawCoverageResultV1",
    "RawCoverageResultV2",
    "ReferenceEvaluationResultV1",
    "ContractSchemaError",
    "json_schema_for",
    "PlanarMetricAdmissionError",
    "Binary64IntervalV1",
    "FilteredPredicateDecisionV1",
    "RuntimePredicateTelemetryV1",
    "build_rational_affine_planar_metric",
    "build_runtime_planar_metric",
    "filtered_orient2d",
    "fraction_from_exact",
    "resolve_orient2d",
    "ContractValidationError",
    "ValidationCode",
    "ValidationIssue",
    "raise_for_issues",
    "validate_analysis_snapshot",
    "validate_decal_request",
    "validate_evaluation_geometry_binding",
    "validate_compiled_plan",
    "validate_chain_straight_evaluation_geometry_binding",
    "validate_geometry_batch",
    "validate_rational_affine_planar_metric",
    "validate_runtime_planar_metric",
    "RuntimeMetricPerformanceReportV1",
    "RuntimeRawCoverageEvaluationV1",
    "evaluate_filtered_runtime_raw_coverage",
    "validate_cross_contract_references",
    "validate_snapshot_request_references",
    "ENVELOPE_DEBUG_SCENE_SCHEMA_V1",
    "EnvelopeDebugStage",
    "DebugPrimitiveKind",
    "DebugDiagnosticSeverity",
    "DebugExactPoint2V1",
    "DebugPatchFrameV1",
    "DebugPointV1",
    "DebugPathV1",
    "DebugLoopV1",
    "DebugRegionV1",
    "DebugLabelV1",
    "DebugDiagnosticV1",
    "EnvelopeDebugSceneV1",
    "build_envelope_debug_scene",
    "validate_envelope_debug_scene",
    "OpaqueId",
    "SourceRevision",
    "PatchId",
    "PatchDomainId",
    "PhysicalChainId",
    "ChainUseId",
    "SourceVertexId",
    "SourceFaceId",
    "SurfaceTriangleId",
    "PhysicalEdgeId",
    "BoundaryLoopId",
    "BoundaryConstraintId",
    "OwnerSectorId",
    "AngleCertificateId",
    "PlanarityCertificateId",
    "ReferenceMetricId",
    "RuntimeMetricId",
    "CornerRelationId",
    "JunctionRelationId",
    "TerminalRelationId",
    "DecalRequestId",
    "FrontSeedId",
    "CornerSeedId",
    "JunctionSeedId",
    "CapSeedId",
    "EndpointClaimSeedId",
    "FrontComponentId",
    "FrontReadingId",
    "SourceSupportId",
    "SelfContactPairDeclarationId",
    "EnvelopeSpecId",
    "EnvelopeInstanceId",
    "HiddenSupportId",
    "SelectionCertificateId",
    "CoverageId",
    "InteractionId",
    "InteractionComponentId",
    "ArrivalModelId",
    "InteractionCandidateId",
    "InteractionRelationId",
    "MutualArrivalCertificateId",
    "EqualityLocusId",
    "EqualityLocusSegmentId",
    "InteractionApplicationId",
    "ResolvedContributionId",
    "SameAlphaInteractionBatchId",
    "ActiveDomainCertificateId",
    "ExactSegmentId",
    "ExactRegionId",
    "ConstructionCertificateId",
    "OwnershipClaimId",
    "EqualityBoundaryId",
    "EventPredicateId",
    "EventTransitionId",
    "TopologyStateVersionId",
    "SameAlphaBatchKeyId",
    "SemanticRegionId",
    "SemanticArrangementId",
    "SemanticBoundaryId",
    "SemanticInterfaceId",
    "SharedSemanticAnchorId",
    "PerPatchProjectionId",
    "RoutePairingId",
    "VertexKey",
    "GeometryFaceId",
    "GeometryDiagnosticId",
    "GeometryStationFactId",
    "SemanticLocationId",
    "MaterialId",
    "LineageId",
    "PolicyId",
    "LawId",
    "ContractVersionId",
    "SymbolicScalarId",
    "EvaluationPlanId",
    "SemanticDigestValue",
    "DebugPrimitiveId",
    "DebugDiagnosticId",
    "MetricSpace",
    "ExactAngleSymbol",
    "SurfaceCoordinateUnavailableReason",
    "IntervalEndpointKind",
    "LocalPoint2V1",
    "LocalVector2V1",
    "LocalPoint3V1",
    "LocalVector3V1",
    "UvPoint2V1",
    "LocalLengthV1",
    "LocalCoordinateV1",
    "SymbolicLocalLengthV1",
    "MetricLengthV1",
    "ExactAngleV1",
    "ExactRatioV1",
    "CertifiedDecimalIntervalV1",
    "UnavailableSourcePositionV1",
    "SourcePositionV1",
    "NamedOutcome",
    "ANALYSIS_SNAPSHOT_SCHEMA_V1",
    "AnalysisCapability",
    "SurfaceRegime",
    "PatchShapeClass",
    "PatchContextTag",
    "BoundaryLoopKind",
    "PhysicalChainKind",
    "ChainUseOrientation",
    "ChainUseRole",
    "BoundaryConstraintKind",
    "BoundaryConstraintTargetUnavailableReason",
    "OwnerInteriorDirection",
    "TurnOrientation",
    "InteriorSelectionLaw",
    "AngleMeasureLaw",
    "AngleMeasureSource",
    "StrictAngleRangeCertificate",
    "ReflexExcessLaw",
    "PatchFrameHandedness",
    "PlanarityLaw",
    "PlanarProjectionLaw",
    "SurfaceMetricAuthority",
    "AngleMeasureUnavailableReason",
    "SupportDirectionUnavailableReason",
    "SupportDirectionAuthority",
    "AngleNormalizationLaw",
    "StationContinuityLaw",
    "JunctionRouteTopologyUnavailableReason",
    "TerminalRelationKind",
    "TerminalEndpointRole",
    "JunctionRelationKind",
    "PlanarityCertificateV1",
    "PlanarSourceVertexCoordinateV1",
    "PlanarPatchFrameV1",
    "IntrinsicSurfaceMetricDescriptorV1",
    "UnavailableSurfaceMetricDescriptorV1",
    "SurfaceMetricDescriptorV1",
    "SourceVertexV1",
    "PatchDescriptorV1",
    "PatchSectorV1",
    "PatchDomainV1",
    "BoundaryLoopV1",
    "PhysicalChainV1",
    "LaunchLocusV1",
    "ChainUseV1",
    "BoundaryConstraintV1",
    "BoundaryLoopConstraintTargetV1",
    "ChainUseConstraintTargetV1",
    "PhysicalEdgeSequenceConstraintTargetV1",
    "UnavailableBoundaryConstraintTargetV1",
    "BoundaryConstraintTargetV1",
    "SourceSupportRefV1",
    "CertifiedPlanarSupportDirectionV1",
    "UnavailableSourceSupportDirectionV1",
    "SourceSupportDirectionPayloadV1",
    "OrientedOwnerSectorV1",
    "ReflexAngleCertificateV1",
    "CertifiedReflexAngleMeasureV1",
    "UnavailableReflexAngleMeasureV1",
    "ReflexAngleMeasurePayloadV1",
    "CornerRelationV1",
    "JunctionRoutePairV1",
    "TJunctionRouteTopologyV1",
    "XJunctionRouteTopologyV1",
    "YJunctionRouteTopologyV1",
    "DeclaredRoutePairsTopologyV1",
    "UnavailableJunctionRouteTopologyV1",
    "JunctionRouteTopologyV1",
    "JunctionRelationV1",
    "TerminalRelationV1",
    "AnalysisSnapshotV1",
    "REFERENCE_PLANAR_METRIC_SCHEMA_V2",
    "RUNTIME_PLANAR_METRIC_SCHEMA_V1",
    "PlanarityAdmissionLawV1",
    "GridSnappingLawV1",
    "GridWindowOutcomeV1",
    "GridScaleSearchOrderV1",
    "GridScaleTrialOutcomeV1",
    "GridScaleTrialV1",
    "IntegerGridCertificateV1",
    "AffineFrameSelectionLawV1",
    "AffineReconstructionLawV1",
    "AffineChartOrientationV1",
    "RuntimePredicateFilterLawV1",
    "RuntimePredicateResultV1",
    "RuntimeMetricFallbackLawV1",
    "MetricSemanticIdentityLawV1",
    "ExactRationalV1",
    "ExactPoint2V1",
    "ExactVector2V1",
    "ExactPoint3V1",
    "ExactVector3V1",
    "ExactMatrix2V1",
    "ExactSourceVertexCoordinateV2",
    "CertifiedAffineSupportDirectionV2",
    "ExactSourcePlaneCertificateV1",
    "RationalAffinePlanarMetricV2",
    "Binary64Point2V1",
    "Binary64Point3V1",
    "Binary64Vector3V1",
    "Binary64Matrix2V1",
    "Binary64SourceVertexCoordinateV1",
    "DerivedBinary64AffineViewV1",
    "RuntimePredicateFilterContractV1",
    "RuntimeMetricFallbackContractV1",
    "RuntimePlanarMetricV1",
    "RawCoverageStage",
    "ResolvedCoverageStage",
    "RawCoverageRef",
    "ResolvedCoverageRef",
    "InteractionKind",
    "CoverageEffect",
    "InteractionDeclarationV1",
    "EnvelopeSpecVariant",
    "StripSupportLawId",
    "StationModelId",
    "TransverseModelId",
    "TerminalInterfacePolicy",
    "AngularSubdivisionPolicy",
    "HiddenSupportDirectionLaw",
    "CertifiedBoundHiddenSupportDirectionLawV1",
    "AdaptiveBoundHiddenSupportDirectionLawV2",
    "EvaluationGeometrySubturnCountLiftLawV1",
    "ExactTurnSignV1",
    "AdaptiveProjectivePoleOwnershipV1",
    "DirectionBindingReasonV1",
    "HiddenSupportScope",
    "AngularExposurePolicy",
    "JunctionSupportLawId",
    "MixedAlphaPolicy",
    "CapClosureLawId",
    "ExactTwoPiHandling",
    "AngularRegressionFixtureId",
    "SelectionLaw",
    "MinimalityLowerBound",
    "AdmissibilityUpperBound",
    "SelectionCertificateAuthority",
    "IntervalBoundKind",
    "BoundaryResolutionState",
    "EffectiveAlphaBindingKind",
    "SelectionIntervalCertificateV1",
    "HuberDensityMidpointSelectionIntervalCertificateV1",
    "HuberDensitySelectionIntervalCertificateV1",
    "AngularProfileSelectionCertificateV1",
    "HiddenSupportSpecV1",
    "DirectionBindingCertificateV1",
    "EvaluationGeometryDirectionBindingCertificateV1",
    "AdaptiveRationalFanOrdinalWindowV2",
    "AdaptiveRationalFanProjectiveChartPieceV1",
    "AdaptiveRationalFanOrdinalWindowAtlasV1",
    "AdaptiveFareyHeightRangeWitnessV2",
    "EvaluationGeometrySubturnCountLiftV1",
    "AdaptiveMinimalRationalFanAuthorityV2",
    "CertifiedBoundHiddenSupportSpecV1",
    "AdaptiveBoundHiddenSupportSpecV2",
    "StripEnvelopeSpec",
    "AngularEnvelopeSpec",
    "AdaptiveDensityAngularEnvelopeSpecV2",
    "JunctionEnvelopeSpec",
    "CapEnvelopeSpec",
    "EnvelopeSpec",
    "EffectiveAlphaBindingV1",
    "EnvelopeInstanceV1",
    "InitialFrontFeatureKind",
    "InitialFrontSourceId",
    "InitialFrontFeatureRefV1",
    "InitialFrontSpec",
    "EventPredicateKind",
    "EventParticipantKind",
    "EventParticipantId",
    "EventParticipantRefV1",
    "EventPredicateDeclarationV1",
    "EventTransitionDeclarationV1",
    "EventLedgerContractId",
    "EventLedgerStartupScope",
    "SuccessorSchedulingPolicy",
    "SameAlphaPolicy",
    "EventPublishPolicy",
    "EventLedgerContractV1",
    "GEOMETRY_BATCH_SCHEMA_V1",
    "GeometryDiagnosticSeverity",
    "GeometryProvenanceV1",
    "GeometryVertexV1",
    "GeometryUvFactV1",
    "GeometryStationFactV1",
    "GeometryFaceV1",
    "GeometrySemanticRegionV1",
    "GeometryBoundaryChainV1",
    "GeometryInterfaceChainV1",
    "GeometryDiagnosticV1",
    "GeometryBatchV1",
    "OwnershipPartitionContractId",
    "OwnershipClaimantKind",
    "SilhouetteEffect",
    "EqualityBoundaryOwner",
    "ClaimInteriorsObligation",
    "ClaimClosureObligation",
    "EqualityBoundaryRef",
    "OwnershipClaimV1",
    "OwnershipPartitionV1",
    "COMPILED_PLAN_SCHEMA_V1",
    "EVALUATION_GEOMETRY_BINDING_SCHEMA_V1",
    "CHAIN_STRAIGHT_EVALUATION_GEOMETRY_BINDING_SCHEMA_V2",
    "EvaluationGeometryBindingLawV1",
    "ChainStraightEvaluationGeometryBindingLawV2",
    "ChainStraightVertexAuthorityV2",
    "ChainStraightAssignmentDispositionV2",
    "EvaluationGeometrySourceVertexV1",
    "EvaluationGeometryBindingV1",
    "ChainStraightVertexAuthorityRecordV2",
    "ChainStraightInternalAssignmentV2",
    "ChainStraightPhysicalChainBindingV2",
    "ChainStraightCapacityDeficitV2",
    "ChainStraightEvaluationGeometryBindingV2",
    "EvaluationGeometryBinding",
    "ActiveIntervalModel",
    "BranchCountPolicy",
    "FrontLifecycle",
    "CapacityReason",
    "FrontTerminalOutcome",
    "StationFlowAuthority",
    "StationAxis",
    "StorageReversalEffect",
    "PlanKeyV1",
    "FrontComponentV1",
    "PhysicalSupportIntervalV1",
    "FrontReadingDeclarationV1",
    "SelfContactPairDeclarationV1",
    "StationFlowV1",
    "GeometryBatchProvenanceV1",
    "CompiledPatchEvaluationPlanV1",
    "CompiledPatchEvaluationPlan",
    "DECAL_REQUEST_SCHEMA_V1",
    "AngularProfileFamilyId",
    "AngularProfileSelectionPolicyId",
    "MaxSubturnParameterId",
    "MaxSubturnValueId",
    "CapPolicyId",
    "BoundaryPolicyId",
    "InteractionPolicyId",
    "OwnershipPolicyId",
    "DecalRequestV1",
    "JunctionProjectionRole",
    "EndpointRole",
    "FrontSeedV1",
    "CornerSeedV1",
    "JunctionSeedV1",
    "CapSeedV1",
    "EndpointClaimSeedV1",
    "SeedV1",
    "SurfacePayloadMode",
    "SourceEdgeV1",
    "SourceFaceV1",
    "SurfaceTriangleV1",
    "PatchSurfaceIRV1",
    "TessellationContractId",
    "TessellationStartStage",
    "SharedVertexKeyPolicy",
    "InternalTessellationVariation",
    "ForbiddenTessellationOperation",
    "TessellationDigestEquivalence",
    "TessellationPlanV1",
    "TessellationPlan",
    "ProjectionAnchorSelectionLawV1",
    "SourceSnapEmbeddingCertificateV1",
    "NearPlanarProjectionEmbeddingCertificateV1",
    "EmbeddingCertifiedRationalAffinePlanarMetricV1",
    "EMBEDDING_CERTIFIED_RATIONAL_AFFINE_PLANAR_METRIC_SCHEMA_V1",
    "EmbeddingCertifiedRationalAffinePlanarMetricCodecV1",
    "build_embedding_certified_rational_affine_planar_metric",
    "validate_embedding_certified_rational_affine_planar_metric",
)

_EXPORT_RANGES = (
    (0, 1, "cftuv_envelope.version"),
    (1, 12, "cftuv_envelope.codec"),
    (12, 18, "cftuv_envelope.canonical"),
    (18, 20, "cftuv_envelope.reference.compile"),
    (20, 22, "cftuv_envelope.reference.raw_coverage"),
    (22, 26, "cftuv_envelope.reference.domain_geometry"),
    (26, 31, "cftuv_envelope.reference.digest"),
    (31, 70, "cftuv_envelope.interactions"),
    (70, 77, "cftuv_envelope.reference.contracts"),
    (77, 80, "cftuv_envelope.reference.provenance"),
    (80, 88, "cftuv_envelope.reference.metric"),
    (88, 105, "cftuv_envelope.reference.contracts"),
    (105, 107, "cftuv_envelope.schema"),
    (107, 116, "cftuv_envelope.planar_metric"),
    (116, 128, "cftuv_envelope.validation"),
    (128, 131, "cftuv_envelope.runtime_metric"),
    (131, 133, "cftuv_envelope.validation"),
    (133, 146, "cftuv_envelope.contracts.debug"),
    (146, 148, "cftuv_envelope.debug_scene"),
    (148, 226, "cftuv_envelope.ids"),
    (226, 244, "cftuv_envelope.numeric"),
    (244, 245, "cftuv_envelope.outcomes"),
    (245, 316, "cftuv_envelope.contracts.analysis"),
    (316, 339, "cftuv_envelope.contracts.metric"),
    (339, 340, "cftuv_envelope.contracts.analysis"),
    (340, 341, "cftuv_envelope.contracts.metric"),
    (341, 342, "cftuv_envelope.contracts.analysis"),
    (342, 351, "cftuv_envelope.contracts.metric"),
    (351, 358, "cftuv_envelope.contracts.coverage"),
    (358, 408, "cftuv_envelope.contracts.envelopes"),
    (408, 424, "cftuv_envelope.contracts.events"),
    (424, 436, "cftuv_envelope.contracts.geometry_batch"),
    (436, 445, "cftuv_envelope.contracts.ownership"),
    (445, 477, "cftuv_envelope.contracts.plan"),
    (477, 478, "cftuv_envelope.contracts.request"),
    (478, 480, "cftuv_envelope.contracts.envelopes"),
    (480, 481, "cftuv_envelope.contracts.request"),
    (481, 482, "cftuv_envelope.contracts.envelopes"),
    (482, 487, "cftuv_envelope.contracts.request"),
    (487, 488, "cftuv_envelope.contracts.seeds"),
    (488, 489, "cftuv_envelope.contracts.envelopes"),
    (489, 494, "cftuv_envelope.contracts.seeds"),
    (494, 495, "cftuv_envelope.contracts.plan"),
    (495, 499, "cftuv_envelope.contracts.surface"),
    (499, 500, "cftuv_envelope.contracts.analysis"),
    (500, 506, "cftuv_envelope.contracts.tessellation"),
    (506, 507, "cftuv_envelope.contracts.plan"),
    (507, 508, "cftuv_envelope.contracts.tessellation"),
    (508, 513, "cftuv_envelope.contracts.metric"),
    (513, 514, "cftuv_envelope.codec"),
    (514, 515, "cftuv_envelope.planar_metric"),
    (515, 516, "cftuv_envelope.validation_metric"),
)

_EXPORTS = {
    name: (module_name, name)
    for start, stop, module_name in _EXPORT_RANGES
    for name in __all__[start:stop]
}

_PRIVATE_MODULES = {
    "_analysis": "cftuv_envelope.contracts.analysis",
    "_coverage": "cftuv_envelope.contracts.coverage",
    "_debug": "cftuv_envelope.contracts.debug",
    "_density_policy": "cftuv_envelope._density_policy",
    "_envelopes": "cftuv_envelope.contracts.envelopes",
    "_events": "cftuv_envelope.contracts.events",
    "_geometry_batch": "cftuv_envelope.contracts.geometry_batch",
    "_ids": "cftuv_envelope.ids",
    "_metric": "cftuv_envelope.contracts.metric",
    "_numeric": "cftuv_envelope.numeric",
    "_outcomes": "cftuv_envelope.outcomes",
    "_ownership": "cftuv_envelope.contracts.ownership",
    "_plan": "cftuv_envelope.contracts.plan",
    "_request": "cftuv_envelope.contracts.request",
    "_seeds": "cftuv_envelope.contracts.seeds",
    "_surface": "cftuv_envelope.contracts.surface",
    "_tessellation": "cftuv_envelope.contracts.tessellation",
}

_CHILD_MODULE_NAMES = (
    "_embedding",
    "adaptive_density_validation",
    "canonical",
    "codec",
    "contracts",
    "debug_scene",
    "exact_sqrt_sum",
    "ids",
    "interactions",
    "numeric",
    "outcomes",
    "planar_metric",
    "reference",
    "robust",
    "runtime_metric",
    "schema",
    "source_grid",
    "validation",
    "validation_issues",
    "validation_metric",
    "version",
    "wavefront",
)

_LEGACY_DIR_EXTRAS = (
    "_PUBLIC_VALUE_MODULES",
    "__all__",
    "__builtins__",
    "__cached__",
    "__doc__",
    "__file__",
    "__loader__",
    "__name__",
    "__package__",
    "__path__",
    "__spec__",
    *_PRIVATE_MODULES,
)


def _hide_child_modules() -> None:
    for child_name in _CHILD_MODULE_NAMES:
        globals().pop(child_name, None)


def __getattr__(name: str):
    target = _EXPORTS.get(name)
    if target is not None:
        module_name, symbol_name = target
        value = getattr(_import_module(module_name), symbol_name)
        _hide_child_modules()
        globals()[name] = value
        return value

    module_name = _PRIVATE_MODULES.get(name)
    if module_name is not None:
        value = _import_module(module_name)
        _hide_child_modules()
        globals()[name] = value
        return value

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted((*__all__, *_LEGACY_DIR_EXTRAS))


class _EnvelopeFacadeModule(_ModuleType):
    """Не даёт importlib расширять исторически замороженный root-фасад."""

    def __setattr__(self, name: str, value) -> None:
        if name in _CHILD_MODULE_NAMES and isinstance(value, _ModuleType):
            return
        super().__setattr__(name, value)

    def __getattribute__(self, name: str):
        if name in _CHILD_MODULE_NAMES:
            module_name = super().__getattribute__("__name__")
            raise AttributeError(
                f"module {module_name!r} has no attribute {name!r}"
            )
        return super().__getattribute__(name)


_hide_child_modules()
_modules[__name__].__class__ = _EnvelopeFacadeModule

# Подпакет-фасад сам лёгкий. Загружаем его один раз, чтобы последующие импорты
# листьев не привязали к родителю исторически скрытое имя `wavefront`.
_import_module("cftuv_envelope.wavefront")
globals().pop("wavefront", None)
