"""Именованные capability outcomes; silent fallback запрещён."""

from enum import Enum


class NamedOutcome(str, Enum):
    DECAL_ANALYSIS_SCHEMA_UNSUPPORTED = "DECAL_ANALYSIS_SCHEMA_UNSUPPORTED"
    BARRIER_SPLIT_REQUIRED = "BARRIER_SPLIT_REQUIRED"
    BARRIER_BYPASS_UNSUPPORTED = "BARRIER_BYPASS_UNSUPPORTED"
    SHARED_ENVELOPE_MIXED_ALPHA_UNPROVEN = "SHARED_ENVELOPE_MIXED_ALPHA_UNPROVEN"
    OWNERSHIP_PARTITION_UNPROVEN = "OWNERSHIP_PARTITION_UNPROVEN"
    PENDING_EXACT_EVALUATION = "PENDING_EXACT_EVALUATION"
    APPROXIMATE_MATERIALIZATION_PENDING = "APPROXIMATE_MATERIALIZATION_PENDING"
    JUNCTION_ROUTE_PAIRING_REQUIRED = "JUNCTION_ROUTE_PAIRING_REQUIRED"

